name: smart-notes

services:
  postgres:
    image: postgres:18-bookworm
    container_name: smart-notes-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: smart-notes-db
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d smart-notes-db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local